services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    networks:
      - todo
  web:
    build: .
    ports:
      - "8081:8081"
      - "8090:8090"
    networks:
      - todo
networks:
  todo:
    driver: bridge