services:
  db:
    image: postgres:15.4
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8081:8081"
      - "8090:8090"
    depends_on:
      - db
    links:
      - "db:localhost"
    command: go run cmd/server/main.go